// This file is auto-generated by Sumi. Do not edit.
// It makes the MiddlewareName type globally available.

declare global {
  export type MiddlewareName = never;
}

// Export an empty object to satisfy TypeScript's module requirement.
export {};
